### ISSUE TITLE
Integrate with Kubernetes

### ISSUE THREAD

**Issue by DazWilkin** [joho/godotenv#51]
Very useful, thank you!

I discovered `godotenv` through a Go sample that uses it. I'm working on running that solution on Kubernetes. One way to solve this with Kubernetes would be to add the `.env` file to the container but this seems to defeat the principle of keeping config externalized.

I used ConfigMaps and am sharing it here for consideration:

There's a [limitation](https://github.com/kubernetes/kubernetes/issues/26299) (!) in ConfigMaps which prevents using them to map a source file containing environment variables or other properties directly into container environment variables.

The workaround is to surface the ConfigMap's contents as a volume in the container but this then requires moving the `.env` (or similarly named file) to a separate directory.

1. Move `.env.` to its own directory and revise the Golang reference. **NB** for convenience I'm using a relative reference here without "./" and I use an absolute reference in the container spec (step 3)
```Go
err := godotenv.Load("config/.env")
```

2. Convert an existing `.env` to a ConfigMap
```bash
kubectl create configmap env --from-file=./config/.env
```

3. The container spec must then reference the ConfigMap (`env`) through a volume mount:
```YAML
spec:
  containers:
  - image: dazwilkin/configmaptest:rpi3
    imagePullPolicy: Always
    name: configmaptest
    ports:
    - name: http
      containerPort: 8080
      protocol: TCP
    volumeMounts:
    - name: config-volume
      mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: configmaptest
```
This results in a container that will run on Kubernetes deriving its env settings from the pod during deployment. The same image may be used in multiple pods each using a different configuration.

Thoughts?
